"use client"; import {FormEvent,useState} from "react";
const sources=["Web","Referral","Event","Cold Outreach","Social","Partner"];
export function CrmForms({entities,userId}:{entities:any[];userId:string}){const [mode,setMode]=useState<"entity"|"deal"|null>(null),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f:any=Object.fromEntries(new FormData(e.currentTarget)),table=mode==="entity"?"entities":"deals";
  if(mode==="entity"){Object.assign(f,{type:"person",is_lead:true,lead_score:f.lead_score?Number(f.lead_score):(f.email?40:20)+(f.phone?20:0),assigned_to:userId})}
  else{f.value=Number(f.value||0);f.discount_percent=Number(f.discount_percent||0)}
  const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({table,data:f})});
  if(r.ok){const row=await r.json();if(mode==="deal"&&f.discount_percent>15)await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({table:"approval_requests",data:{kind:"deal_discount",record_table:"deals",record_id:row.id,reason:`${f.discount_percent}% discount requested on ${f.title}`}})});location.reload()}
  else{alert((await r.json()).error);setBusy(false)}}
 return <div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("entity")}>New lead</button><button className="btn" onClick={()=>setMode("deal")}>New deal</button>{mode&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={()=>setMode(null)}><form className="w-full max-w-md rounded-2xl bg-cream p-6" onSubmit={save} onClick={e=>e.stopPropagation()}><h2 className="mb-5 text-2xl font-black">{mode==="entity"?"Capture lead":"New deal"}</h2>{mode==="entity"?<div className="space-y-3"><input className="input" name="name" placeholder="Full name" required/><input className="input" name="email" type="email" placeholder="Email"/><input className="input" name="phone" placeholder="Phone"/><select className="input" name="lead_source" defaultValue=""><option value="">Lead source…</option>{sources.map(s=><option key={s}>{s}</option>)}</select><input className="input" name="territory" placeholder="Territory / region"/></div>:<div className="space-y-3"><input className="input" name="title" placeholder="Deal title" required/><select className="input" name="entity_id" required><option value="">Select contact</option>{entities.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input className="input" name="value" type="number" placeholder="Value"/><select className="input" name="stage">{["Lead","Qualified","Proposal","Negotiation"].map(x=><option key={x}>{x}</option>)}</select><label><span className="label">Discount % (over 15% needs approval)</span><input className="input" name="discount_percent" type="number" step="any" placeholder="0"/></label></div>}<button disabled={busy} className="btn mt-5 w-full">{busy?"Saving…":"Save"}</button></form></div>}</div>}
