"use client";
import { FormEvent, ReactNode, useState } from "react";

async function mutate(method:"POST"|"PATCH",body:any){
 const r=await fetch("/api/records",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});
 const x=await r.json(); if(!r.ok)throw Error(x.error||"Unable to save"); return x;
}
function Modal({title,open,onClose,children}:{title:string;open:boolean;onClose:()=>void;children:ReactNode}){
 if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onMouseDown={onClose}><div className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-cream p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>
}
function FormButton({children,busy}:{children:ReactNode,busy:boolean}){return <button disabled={busy} className="btn mt-5 w-full">{busy?"Saving…":children}</button>}

export function CrmTaskActions({entities,tasks}:{entities:any[];tasks:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=Object.fromEntries(new FormData(e.currentTarget));await mutate("POST",{table:"tasks",data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(t:any){await mutate("PATCH",{table:"tasks",id:t.id,data:{completed:!t.completed}});location.reload()}
 return <section className="card mt-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Follow-ups</h2><p className="text-sm text-black/45">Tasks connected to the shared customer record.</p></div><button className="btn-secondary" onClick={()=>setOpen(true)}>New task</button></div><div className="mt-4 divide-y">{tasks.length?tasks.map(t=><button onClick={()=>toggle(t)} className="flex w-full items-center justify-between py-3 text-left" key={t.id}><span><b className={t.completed?"line-through opacity-40":""}>{t.title}</b><span className="ml-2 text-xs text-black/40">{t.entities?.name||"General"} · {t.due_at?new Date(t.due_at).toLocaleDateString():"No due date"}</span></span><span className="text-xs font-bold text-moss">{t.completed?"Reopen":"Complete"}</span></button>):<p className="py-8 text-sm text-black/40">No follow-ups yet.</p>}</div><Modal title="New follow-up" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><input className="input" name="title" placeholder="Task title" required/><select className="input" name="entity_id"><option value="">General task</option>{entities.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><input className="input" name="due_at" type="datetime-local"/><FormButton busy={busy}>Create follow-up</FormButton></form></Modal></section>
}

export function ErpActions({vendors,customers}:{vendors:any[];customers:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));let table=mode;if(mode==="vendor"){table="entities";Object.assign(f,{type:"company",is_vendor:true})}if(mode==="purchase_orders")f.items=[{description:f.description,quantity:Number(f.quantity||1),price:Number(f.total||0)}];if(mode==="invoices")f.items=[{description:f.description,amount:Number(f.amount||0)}];delete f.description;delete f.quantity;await mutate("POST",{table,data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setMode("vendor")}>New vendor</button><button className="btn-secondary" onClick={()=>setMode("purchase_orders")}>New PO</button><button className="btn" onClick={()=>setMode("invoices")}>New invoice</button></div><Modal title={mode==="vendor"?"New vendor":mode==="purchase_orders"?"New purchase order":"New invoice"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3">{mode==="vendor"?<><input className="input" name="name" placeholder="Vendor name" required/><input className="input" name="email" type="email" placeholder="Email"/><input className="input" name="phone" placeholder="Phone"/></>:mode==="purchase_orders"?<><select className="input" name="vendor_id" required><option value="">Select vendor</option>{vendors.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><input className="input" name="po_number" placeholder="PO number" required/><input className="input" name="description" placeholder="Item description" required/><input className="input" name="quantity" type="number" min="1" placeholder="Quantity"/><input className="input" name="total" type="number" step=".01" placeholder="Total"/><select className="input" name="status"><option>draft</option><option>approved</option><option>ordered</option><option>received</option></select><input className="input" name="expected_on" type="date"/></>:<><select className="input" name="customer_id" required><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input className="input" name="invoice_number" placeholder="Invoice number" required/><input className="input" name="description" placeholder="Line item" required/><input className="input" name="amount" type="number" step=".01" placeholder="Amount" required/><input className="input" name="due_on" type="date"/><select className="input" name="status"><option>draft</option><option>sent</option><option>paid</option><option>overdue</option></select></>}<FormButton busy={busy}>Save record</FormButton></form></Modal></>
}

export function InventoryAssetActions({employees,assets}:{employees:any[];assets:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));if(mode==="asset")await mutate("POST",{table:"assets",data:{...f,status:"available"}});else await mutate("PATCH",{table:"assets",id:f.id,data:{assigned_employee_id:f.assigned_employee_id||null,status:f.assigned_employee_id?"checked_out":"available",checked_out_at:f.assigned_employee_id?new Date().toISOString():null}});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("asset")}>New asset</button><button className="btn-secondary" onClick={()=>setMode("checkout")}>Asset checkout</button></div><Modal title={mode==="asset"?"Register asset":"Checkout / return asset"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3">{mode==="asset"?<><input className="input" name="name" placeholder="Asset name" required/><input className="input" name="asset_tag" placeholder="Asset tag" required/><input className="input" name="serial_number" placeholder="Serial number"/></>:<><select className="input" name="id" required><option value="">Select asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.status}</option>)}</select><select className="input" name="assigned_employee_id"><option value="">Return to inventory</option>{employees.map(e=><option value={e.id} key={e.id}>{e.entities?.name}</option>)}</select></>}<FormButton busy={busy}>Save asset</FormButton></form></Modal></>
}

export function PeopleOpsActions({employees,onboarding}:{employees:any[];onboarding:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));if(mode==="attendance")f.clock_in=new Date().toISOString();await mutate("POST",{table:mode,data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(x:any){await mutate("PATCH",{table:"onboarding_items",id:x.id,data:{completed:!x.completed}});location.reload()}
 return <section className="card"><div className="flex items-center justify-between"><h2 className="text-xl font-black">People operations</h2><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("attendance")}>Clock in</button><button className="btn-secondary" onClick={()=>setMode("onboarding_items")}>Onboarding task</button></div></div><div className="mt-4 divide-y">{onboarding.map(x=><button onClick={()=>toggle(x)} className="flex w-full justify-between py-3 text-left text-sm" key={x.id}><span className={x.completed?"line-through opacity-40":""}>{x.title} · {x.employees?.entities?.name}</span><b className="text-moss">{x.completed?"Reopen":"Complete"}</b></button>)}</div><Modal title={mode==="attendance"?"Clock in":"New onboarding task"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3"><select className="input" name="employee_id" required>{employees.map(e=><option value={e.id} key={e.id}>{e.entities?.name}</option>)}</select>{mode==="attendance"?<input className="input" name="notes" placeholder="Notes"/>:<><input className="input" name="title" placeholder="Task" required/><input className="input" name="due_on" type="date"/></>}<FormButton busy={busy}>Save</FormButton></form></Modal></section>
}

export function AutomationActions({rules}:{rules:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));const condition=f.condition_value?{field:f.condition_field,operator:f.condition_operator,value:f.condition_value}:{};delete f.condition_field;delete f.condition_operator;delete f.condition_value;await mutate("POST",{table:"automation_rules",data:{...f,condition}});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(r:any){await mutate("PATCH",{table:"automation_rules",id:r.id,data:{enabled:!r.enabled}});location.reload()}
 return <><button className="btn" onClick={()=>setOpen(true)}>Build workflow</button><Modal title="Trigger → condition → action" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><input className="input" name="name" placeholder="Workflow name" required/><label className="label">When</label><select className="input" name="trigger_key"><option value="inventory.low">Inventory becomes low</option><option value="deal.won">Deal moves to Won</option><option value="leave.approved">Leave is approved</option></select><label className="label">Optional condition</label><div className="grid grid-cols-3 gap-2"><input className="input" name="condition_field" placeholder="field"/><select className="input" name="condition_operator"><option value="equals">equals</option><option value="gt">greater than</option><option value="lt">less than</option><option value="contains">contains</option></select><input className="input" name="condition_value" placeholder="value"/></div><label className="label">Then</label><select className="input" name="action_key"><option value="draft_po">Draft purchase order + notify</option><option value="customer_invoice">Create customer + invoice</option><option value="leave_calendar">Notify + block calendar</option></select><FormButton busy={busy}>Activate workflow</FormButton></form></Modal><div className="mt-4 flex flex-wrap gap-2">{rules.map(r=><button className="rounded-full border px-3 py-1 text-xs font-bold" onClick={()=>toggle(r)} key={r.id}>{r.enabled?"Pause":"Activate"} · {r.name}</button>)}</div></>
}
