"use client";
import { FormEvent, useState } from "react";
import { mutate, Modal, FormButton } from "@/components/ui-kit";

export function CrmTaskActions({entities,tasks}:{entities:any[];tasks:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=Object.fromEntries(new FormData(e.currentTarget));await mutate("POST",{table:"tasks",data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(t:any){await mutate("PATCH",{table:"tasks",id:t.id,data:{completed:!t.completed}});location.reload()}
 return <section className="card mt-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Follow-ups</h2><p className="text-sm text-black/45">Tasks connected to the shared customer record.</p></div><button className="btn-secondary" onClick={()=>setOpen(true)}>New task</button></div><div className="mt-4 divide-y">{tasks.length?tasks.map(t=><button onClick={()=>toggle(t)} className="flex w-full items-center justify-between py-3 text-left" key={t.id}><span><b className={t.completed?"line-through opacity-40":""}>{t.title}</b><span className="ml-2 text-xs text-black/40">{t.entities?.name||"General"} · {t.due_at?new Date(t.due_at).toLocaleDateString():"No due date"}</span></span><span className="text-xs font-bold text-moss">{t.completed?"Reopen":"Complete"}</span></button>):<p className="py-8 text-sm text-black/40">No follow-ups yet.</p>}</div><Modal title="New follow-up" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><input className="input" name="title" placeholder="Task title" required/><select className="input" name="entity_id"><option value="">General task</option>{entities.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><input className="input" name="due_at" type="datetime-local"/><FormButton busy={busy}>Create follow-up</FormButton></form></Modal></section>
}

export function ErpActions({vendors,customers}:{vendors:any[];customers:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));let table=mode;if(mode==="vendor"){table="entities";Object.assign(f,{type:"company",is_vendor:true})}if(mode==="purchase_orders")f.items=[{description:f.description,quantity:Number(f.quantity||1),price:Number(f.total||0)}];if(mode==="invoices")f.items=[{description:f.description,amount:Number(f.amount||0)}];delete f.description;delete f.quantity;await mutate("POST",{table,data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setMode("vendor")}>New vendor</button><button className="btn-secondary" onClick={()=>setMode("purchase_orders")}>New PO</button><button className="btn" onClick={()=>setMode("invoices")}>New invoice</button></div><Modal title={mode==="vendor"?"New vendor":mode==="purchase_orders"?"New purchase order":"New invoice"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3">{mode==="vendor"?<><input className="input" name="name" placeholder="Vendor name" required/><input className="input" name="email" type="email" placeholder="Email"/><input className="input" name="phone" placeholder="Phone"/></>:mode==="purchase_orders"?<><select className="input" name="vendor_id" required><option value="">Select vendor</option>{vendors.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><input className="input" name="po_number" placeholder="PO number" required/><input className="input" name="description" placeholder="Item description" required/><input className="input" name="quantity" type="number" min="1" placeholder="Quantity"/><input className="input" name="total" type="number" step=".01" placeholder="Total"/><select className="input" name="status"><option>draft</option><option>approved</option><option>ordered</option><option>received</option></select><input className="input" name="expected_on" type="date"/></>:<><select className="input" name="customer_id" required><option value="">Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input className="input" name="invoice_number" placeholder="Invoice number" required/><input className="input" name="description" placeholder="Line item" required/><input className="input" name="amount" type="number" step=".01" placeholder="Amount" required/><input className="input" name="due_on" type="date"/><select className="input" name="status"><option>draft</option><option>sent</option><option>paid</option><option>overdue</option></select></>}<FormButton busy={busy}>Save record</FormButton></form></Modal></>
}

export function InventoryAssetActions({employees,assets}:{employees:any[];assets:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));if(mode==="asset")await mutate("POST",{table:"assets",data:{...f,status:"available"}});else await mutate("PATCH",{table:"assets",id:f.id,data:{assigned_employee_id:f.assigned_employee_id||null,status:f.assigned_employee_id?"checked_out":"available",checked_out_at:f.assigned_employee_id?new Date().toISOString():null}});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("asset")}>New asset</button><button className="btn-secondary" onClick={()=>setMode("checkout")}>Asset checkout</button></div><Modal title={mode==="asset"?"Register asset":"Checkout / return asset"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3">{mode==="asset"?<><input className="input" name="name" placeholder="Asset name" required/><input className="input" name="asset_tag" placeholder="Asset tag" required/><input className="input" name="serial_number" placeholder="Serial number"/></>:<><select className="input" name="id" required><option value="">Select asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.status}</option>)}</select><select className="input" name="assigned_employee_id"><option value="">Return to inventory</option>{employees.map(e=><option value={e.id} key={e.id}>{e.entities?.name}</option>)}</select></>}<FormButton busy={busy}>Save asset</FormButton></form></Modal></>
}

export function PeopleOpsActions({employees,onboarding}:{employees:any[];onboarding:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));if(mode==="attendance")f.clock_in=new Date().toISOString();await mutate("POST",{table:mode,data:f});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(x:any){await mutate("PATCH",{table:"onboarding_items",id:x.id,data:{completed:!x.completed}});location.reload()}
 return <section className="card"><div className="flex items-center justify-between"><h2 className="text-xl font-black">People operations</h2><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("attendance")}>Clock in</button><button className="btn-secondary" onClick={()=>setMode("onboarding_items")}>Onboarding task</button></div></div><div className="mt-4 divide-y">{onboarding.map(x=><button onClick={()=>toggle(x)} className="flex w-full justify-between py-3 text-left text-sm" key={x.id}><span className={x.completed?"line-through opacity-40":""}>{x.title} · {x.employees?.entities?.name}</span><b className="text-moss">{x.completed?"Reopen":"Complete"}</b></button>)}</div><Modal title={mode==="attendance"?"Clock in":"New onboarding task"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3"><select className="input" name="employee_id" required>{employees.map(e=><option value={e.id} key={e.id}>{e.entities?.name}</option>)}</select>{mode==="attendance"?<input className="input" name="notes" placeholder="Notes"/>:<><input className="input" name="title" placeholder="Task" required/><input className="input" name="due_on" type="date"/></>}<FormButton busy={busy}>Save</FormButton></form></Modal></section>
}

export function AutomationActions({rules}:{rules:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));const condition=f.condition_value?{field:f.condition_field,operator:f.condition_operator,value:f.condition_value}:{};delete f.condition_field;delete f.condition_operator;delete f.condition_value;await mutate("POST",{table:"automation_rules",data:{...f,condition}});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 async function toggle(r:any){await mutate("PATCH",{table:"automation_rules",id:r.id,data:{enabled:!r.enabled}});location.reload()}
 return <><button className="btn" onClick={()=>setOpen(true)}>Build workflow</button><Modal title="Trigger → condition → action" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><input className="input" name="name" placeholder="Workflow name" required/><label className="label">When</label><select className="input" name="trigger_key"><option value="inventory.low">Inventory becomes low</option><option value="deal.won">Deal moves to Won</option><option value="leave.approved">Leave is approved</option><option value="expense.approved">Expense is approved</option><option value="case.urgent">Urgent case is opened</option><option value="webhook.custom">Inbound webhook received</option></select><label className="label">Optional condition</label><div className="grid grid-cols-3 gap-2"><input className="input" name="condition_field" placeholder="field"/><select className="input" name="condition_operator"><option value="equals">equals</option><option value="gt">greater than</option><option value="lt">less than</option><option value="contains">contains</option></select><input className="input" name="condition_value" placeholder="value"/></div><label className="label">Then</label><select className="input" name="action_key"><option value="draft_po">Draft purchase order + notify</option><option value="customer_invoice">Create customer + invoice</option><option value="leave_calendar">Notify + block calendar</option><option value="expense_ledger">Post ledger entry + notify</option><option value="case_notify">Notify support team</option></select><FormButton busy={busy}>Activate workflow</FormButton></form></Modal><div className="mt-4 flex flex-wrap gap-2">{rules.map(r=><button className="rounded-full border px-3 py-1 text-xs font-bold" onClick={()=>toggle(r)} key={r.id}>{r.enabled?"Pause":"Activate"} · {r.name}</button>)}</div></>
}

export function AssignToMe({id,mine,userId}:{id:string;mine:boolean;userId:string}){
 const[busy,setBusy]=useState(false);
 async function run(){setBusy(true);await mutate("PATCH",{table:"entities",id,data:{assigned_to:mine?null:userId}});location.reload()}
 return <button disabled={busy} onClick={run} className={`text-xs font-bold ${mine?"text-black/40 hover:text-red-600":"text-moss"}`}>{mine?"Unassign":"Claim"}</button>
}

export function QuoteActions({entities,deals}:{entities:any[];deals:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));const amount=Number(f.amount||0);await mutate("POST",{table:"quotes",data:{entity_id:f.entity_id,deal_id:f.deal_id||null,quote_number:`QUO-${Date.now().toString().slice(-6)}`,valid_until:f.valid_until||null,items:[{description:f.description,amount}],subtotal:amount,total:amount}});location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><button className="btn-secondary" onClick={()=>setOpen(true)}>New quote</button><Modal title="New quote" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><select className="input" name="entity_id" required><option value="">Customer / contact</option>{entities.map((e:any)=><option value={e.id} key={e.id}>{e.name}</option>)}</select><select className="input" name="deal_id"><option value="">Link to deal (optional)</option>{deals.map((d:any)=><option value={d.id} key={d.id}>{d.title}</option>)}</select><input className="input" name="description" placeholder="Line item description" required/><input className="input" name="amount" type="number" step="any" placeholder="Amount" required/><input className="input" name="valid_until" type="date"/><FormButton busy={busy}>Create quote</FormButton></form></Modal></>
}
export function QuoteRow({q}:{q:any}){
 const[busy,setBusy]=useState(false);
 async function send(){setBusy(true);await mutate("PATCH",{table:"quotes",id:q.id,data:{status:"sent"}});location.reload()}
 async function accept(){setBusy(true);await mutate("PATCH",{table:"quotes",id:q.id,data:{status:"accepted"}});location.reload()}
 async function convert(){setBusy(true);const r=await fetch("/api/quotes/convert",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quote_id:q.id})});if(r.ok)location.reload();else{alert((await r.json()).error);setBusy(false)}}
 return <div className="flex items-center justify-between py-3 text-sm" key={q.id}><div><b>{q.quote_number} · {q.entities?.name}</b><p className="text-xs text-black/40 capitalize">{q.status} · ${Number(q.total).toLocaleString()}</p></div><div className="flex gap-3">{q.status==="draft"&&<button disabled={busy} onClick={send} className="text-xs font-bold text-moss">Send</button>}{q.status==="sent"&&<button disabled={busy} onClick={accept} className="text-xs font-bold text-moss">Mark accepted</button>}{q.status==="accepted"&&<button disabled={busy} onClick={convert} className="text-xs font-bold text-ink">Convert to order</button>}</div></div>
}

export function CaseActions({entities}:{entities:any[]}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(f)});if(!r.ok)throw Error((await r.json()).error);location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><button className="btn-secondary" onClick={()=>setOpen(true)}>New case</button><Modal title="New support case" open={open} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><input className="input" name="subject" placeholder="Subject" required/><select className="input" name="entity_id"><option value="">General</option>{entities.map((e:any)=><option value={e.id} key={e.id}>{e.name}</option>)}</select><select className="input" name="priority" defaultValue="normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent (auto-notifies support)</option></select><textarea className="input" name="description" placeholder="Description" rows={3}/><FormButton busy={busy}>Open case</FormButton></form></Modal></>
}
export function CaseRow({c}:{c:any}){
 const[busy,setBusy]=useState(false);
 async function decide(status:string){setBusy(true);const r=await fetch("/api/cases",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:c.id,status})});if(r.ok)location.reload();else{alert((await r.json()).error);setBusy(false)}}
 const sla=new Date(new Date(c.created_at).getTime()+c.sla_hours*3600000);
 return <div className="flex items-center justify-between py-3 text-sm"><div><b>{c.subject}</b><p className="text-xs text-black/40">{c.entities?.name||"General"} · SLA {sla.toLocaleString()} {c.priority==="urgent"&&<span className="ml-1 font-bold text-red-600">URGENT</span>}</p></div>{c.status==="resolved"||c.status==="closed"?<span className="text-xs font-bold capitalize text-black/40">{c.status}</span>:<div className="flex gap-3"><button disabled={busy} onClick={()=>decide("resolved")} className="text-xs font-bold text-moss">Resolve</button><button disabled={busy} onClick={()=>decide("closed")} className="text-xs font-bold text-black/40">Close</button></div>}</div>
}

export function CampaignActions({entities,campaigns}:{entities:any[];campaigns:any[]}){
 const[mode,setMode]=useState(""),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f:any=Object.fromEntries(new FormData(e.currentTarget));
  if(mode==="campaign")await mutate("POST",{table:"campaigns",data:{...f,budget:Number(f.budget||0),expected_revenue:Number(f.expected_revenue||0)}});
  else{const ids=(new FormData(e.currentTarget)).getAll("entity_ids") as string[];for(const entity_id of ids)await mutate("POST",{table:"campaign_members",data:{campaign_id:f.campaign_id,entity_id}})}
  location.reload()}catch(x:any){alert(x.message);setBusy(false)}}
 return <><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setMode("campaign")}>New campaign</button><button className="btn" onClick={()=>setMode("members")}>Add members</button></div><Modal title={mode==="campaign"?"New campaign":"Add campaign members"} open={!!mode} onClose={()=>setMode("")}><form onSubmit={save} className="space-y-3">{mode==="campaign"?<><input className="input" name="name" placeholder="Campaign name" required/><select className="input" name="type"><option value="email">Email</option><option value="social">Social</option><option value="event">Event</option><option value="webinar">Webinar</option></select><input className="input" name="start_date" type="date"/><input className="input" name="end_date" type="date"/><input className="input" name="budget" type="number" placeholder="Budget"/><input className="input" name="expected_revenue" type="number" placeholder="Expected revenue"/></>:<><select className="input" name="campaign_id" required><option value="">Select campaign</option>{campaigns.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><div className="max-h-48 space-y-1 overflow-auto rounded-xl border p-2">{entities.map((e:any)=><label key={e.id} className="flex items-center gap-2 text-sm"><input type="checkbox" name="entity_ids" value={e.id}/>{e.name}</label>)}</div></>}<FormButton busy={busy}>Save</FormButton></form></Modal></>
}

export function ApprovalRow({a}:{a:any}){
 const[busy,setBusy]=useState(false);
 async function decide(status:"approved"|"rejected"){setBusy(true);await mutate("PATCH",{table:"approval_requests",id:a.id,data:{status}});if(a.record_table==="deals")await mutate("PATCH",{table:"deals",id:a.record_id,data:{approval_status:status}});location.reload()}
 return <div className="flex items-center justify-between py-3 text-sm"><div><b className="capitalize">{a.kind.replace("_"," ")}</b><p className="text-xs text-black/40">{a.reason}</p></div>{a.status==="pending"?<div className="flex gap-3"><button disabled={busy} onClick={()=>decide("approved")} className="text-xs font-bold text-moss">Approve</button><button disabled={busy} onClick={()=>decide("rejected")} className="text-xs font-bold text-red-600">Reject</button></div>:<span className="text-xs font-bold capitalize text-black/40">{a.status}</span>}</div>
}
