import { NextResponse } from "next/server"; import { createClient } from "@/lib/supabase/server";
const allowed=["entities","deals","tasks","inventory_items","stock_movements","assets","employees","leave_requests","attendance","onboarding_items","purchase_orders","invoices","ledger_entries","automation_rules",
 "cases","campaigns","campaign_members","quotes","approval_requests","sales_orders","bills","expenses","budgets","recurring_invoices",
 "job_postings","candidates","performance_reviews","goals","benefit_plans","benefit_enrollments","hr_documents",
 "warehouses","item_variants","item_components","item_serials","webhooks","automation_credentials"];
async function ctx(){const db=createClient(),{data:{user}}=await db.auth.getUser();if(!user)throw Error("Unauthorized");const {data:m}=await db.from("org_members").select("org_id").eq("user_id",user.id).limit(1).single();if(!m)throw Error("No organization");return{db,user,org_id:m.org_id}}
export async function POST(req:Request){try{const {table,data}=await req.json();if(!allowed.includes(table))throw Error("Invalid table");const c=await ctx(),{data:row,error}=await c.db.from(table).insert({...data,org_id:c.org_id}).select().single();if(error)throw error;await c.db.from("usage_events").insert({org_id:c.org_id,module:table,event_name:"record_created"});return NextResponse.json(row)}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
export async function PATCH(req:Request){try{const {table,id,data}=await req.json();if(!allowed.includes(table))throw Error("Invalid table");const c=await ctx(),{data:row,error}=await c.db.from(table).update(data).eq("id",id).eq("org_id",c.org_id).select().single();if(error)throw error;return NextResponse.json(row)}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
export async function DELETE(req:Request){try{const {table,id}=await req.json();if(!allowed.includes(table))throw Error("Invalid table");const c=await ctx(),{error}=await c.db.from(table).delete().eq("id",id).eq("org_id",c.org_id);if(error)throw error;return NextResponse.json({ok:true})}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
