import{getContext}from"@/lib/context";import{PageHeader}from"@/components/page-header";import{AutomationActions}from"@/components/module-actions";import{Bot,CheckCircle2,GitBranch,Zap,Webhook,KeyRound}from"lucide-react";
import{TemplateGallery,WebhookActions,WebhookRow,CredentialActions,CredentialRow,TestRunButton}from"@/components/automation-extras";
import{ListSection}from"@/components/list-section";import{headers}from"next/headers";
const labels:Record<string,string>={"inventory.low":"Stock falls below reorder point","deal.won":"Deal moves to Won","leave.approved":"Leave request is approved","expense.approved":"Expense is approved","case.urgent":"Urgent case is opened","webhook.custom":"Inbound webhook received",draft_po:"Draft PO + notification",customer_invoice:"Customer + invoice",leave_calendar:"Notify + calendar block",expense_ledger:"Post ledger entry + notify",case_notify:"Notify support team"};
export default async function Automation(){const{db,member}=await getContext(),oid=member.org_id;
 const[{data:rules},{data:runs},{data:webhooks},{data:credentials}]=await Promise.all([
  db.from("automation_rules").select("*").eq("org_id",oid).order("created_at"),
  db.from("automation_runs").select("*,automation_rules(name)").eq("org_id",oid).order("created_at",{ascending:false}).limit(12),
  db.from("webhooks").select("*").eq("org_id",oid).order("created_at",{ascending:false}),
  db.from("automation_credentials").select("*").eq("org_id",oid).order("created_at",{ascending:false})]);
 const h=headers(),proto=h.get("x-forwarded-proto")||"https",host=h.get("host"),baseUrl=process.env.NEXT_PUBLIC_APP_URL||`${proto}://${host}`;
 return <><PageHeader eyebrow="Automation · Visual workflows" title="Make work flow itself"><AutomationActions rules={rules||[]}/></PageHeader>
 <div className="rounded-2xl bg-lime/40 p-5"><div className="flex gap-3"><Zap className="text-moss"/><div><b>Trigger → condition → action, across every module.</b><p className="mt-1 text-sm text-black/55">Each workflow creates real records, meters usage, and writes an auditable run. Start from a template below or build your own.</p></div></div></div>
 <h2 className="mb-3 mt-6 text-lg font-black">Workflow templates</h2><TemplateGallery/>
 <div className="mt-8 grid gap-4 lg:grid-cols-3">{rules?.map(r=><div className="card" key={r.id}><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-lime"><Bot size={18}/></span><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.enabled?"bg-green-100 text-green-800":"bg-black/5"}`}>{r.enabled?"Active":"Paused"}</span></div><h3 className="mt-5 text-lg font-black">{r.name}</h3><div className="mt-4 space-y-2 text-sm"><p className="rounded-xl bg-black/5 p-3"><b>WHEN</b> · {labels[r.trigger_key]||r.trigger_key}</p>{Object.keys(r.condition||{}).length>0&&<p className="rounded-xl bg-black/5 p-3"><b>IF</b> · {r.condition.field} {r.condition.operator} {String(r.condition.value)}</p>}<p className="rounded-xl bg-black/5 p-3"><b>THEN</b> · {labels[r.action_key]||r.action_key}</p></div><div className="mt-4 flex items-center justify-between"><p className="text-xs text-black/40">{r.runs} successful runs</p><TestRunButton ruleId={r.id}/></div></div>)}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2">
  <ListSection title="Inbound webhooks" icon={<Webhook size={18}/>} action={<WebhookActions/>} empty="No webhooks yet — create one to trigger workflows from any external system.">{webhooks?.map((w:any)=><WebhookRow w={w} baseUrl={baseUrl} key={w.id}/>)}</ListSection>
  <ListSection title="Credential vault" icon={<KeyRound size={18}/>} action={<CredentialActions/>} empty="No credentials stored yet.">{credentials?.map((c:any)=><CredentialRow c={{id:c.id,name:c.name,kind:c.kind,masked:`••••${String(c.value).slice(-4)}`}} key={c.id}/>)}</ListSection>
 </div>
 <section className="card mt-6"><h2 className="text-xl font-black">Execution history</h2><div className="mt-4 divide-y">{runs?.length?runs.map(r=><div className="flex items-center gap-3 py-3" key={r.id}>{r.status==="success"?<CheckCircle2 className="text-green-600" size={18}/>:<GitBranch className="text-red-600" size={18}/>}<div><p className="text-sm font-bold">{r.automation_rules?.name||"Automation"} · {r.status}</p><p className="text-xs text-black/40">{new Date(r.created_at).toLocaleString()}{r.error?` · ${r.error}`:""}</p></div></div>):<p className="py-8 text-center text-sm text-black/40">Workflow runs will appear here.</p>}</div></section>
 </>}
