import{NextResponse}from"next/server";import{createClient}from"@/lib/supabase/server";import{runAutomations}from"@/lib/automation";
export async function POST(){try{const db=createClient(),{data:{user}}=await db.auth.getUser();if(!user)throw Error("Unauthorized");const{data:m}=await db.from("org_members").select("org_id").eq("user_id",user.id).single(),org_id=m!.org_id;const{count}=await db.from("deals").select("*",{count:"exact",head:true}).eq("org_id",org_id);if(count)return NextResponse.json({ok:true,existing:true});
 const{data:entities,error:e}=await db.from("entities").insert([
  {org_id,type:"company",name:"Northstar Labs",email:"hello@northstarlabs.co",is_lead:true,tags:["SaaS","Priority"]},
  {org_id,type:"company",name:"Studio Kindred",email:"ops@studiokindred.com",is_customer:true},
  {org_id,type:"company",name:"Apex Office Supply",email:"orders@apexoffice.co",is_vendor:true},
  {org_id,type:"person",name:"Maya Chen",email:"maya@erica.demo",is_employee:true},
  {org_id,type:"person",name:"Jon Bell",email:"jon@erica.demo",is_employee:true}
 ]).select();if(e)throw e;const north=entities![0],kindred=entities![1],vendor=entities![2],maya=entities![3],jon=entities![4];
 const{data:employees}=await db.from("employees").insert([{org_id,entity_id:maya.id,job_title:"Head of Growth",department:"Revenue",start_date:"2026-02-03"},{org_id,entity_id:jon.id,job_title:"Operations Lead",department:"Operations",start_date:"2026-03-10"}]).select();
 const{data:rules}=await db.from("automation_rules").insert([{org_id,name:"Restock before we run out",trigger_key:"inventory.low",action_key:"draft_po"},{org_id,name:"Turn wins into revenue",trigger_key:"deal.won",action_key:"customer_invoice"},{org_id,name:"Keep leave in sync",trigger_key:"leave.approved",action_key:"leave_calendar"}]).select();
 const{data:deals}=await db.from("deals").insert([{org_id,entity_id:north.id,title:"Northstar expansion",value:42000,stage:"Won",probability:100},{org_id,entity_id:kindred.id,title:"Kindred services renewal",value:18500,stage:"Negotiation",probability:80},{org_id,entity_id:north.id,title:"Analytics rollout",value:12000,stage:"Proposal",probability:55}]).select("*,entities(*)");
 const{data:items}=await db.from("inventory_items").insert([{org_id,sku:"LAP-14-PRO",name:"14-inch Pro Laptop",quantity:2,reorder_point:3,unit_cost:1299},{org_id,sku:"HEAD-NC-01",name:"Noise-canceling Headset",quantity:18,reorder_point:5,unit_cost:189},{org_id,sku:"DOCK-USBC",name:"USB-C Dock",quantity:7,reorder_point:4,unit_cost:119}]).select();
 await db.from("assets").insert([{org_id,name:"MacBook Pro — Maya",asset_tag:"ERICA-001",status:"checked_out",assigned_employee_id:employees![0].id,checked_out_at:new Date().toISOString()},{org_id,name:"Dell XPS — Jon",asset_tag:"ERICA-002",status:"checked_out",assigned_employee_id:employees![1].id,checked_out_at:new Date().toISOString()}]);
 const{data:leave}=await db.from("leave_requests").insert({org_id,employee_id:employees![0].id,leave_type:"Vacation",starts_on:"2026-08-10",ends_on:"2026-08-14",reason:"Family trip",status:"approved",reviewed_by:user.id,reviewed_at:new Date().toISOString()}).select().single();
 await db.from("onboarding_items").insert([{org_id,employee_id:employees![1].id,title:"Complete security training",completed:true},{org_id,employee_id:employees![1].id,title:"Meet department leads",completed:false}]);
 await db.from("attendance").insert([{org_id,employee_id:employees![0].id,clock_in:new Date(Date.now()-8*3600000).toISOString(),clock_out:new Date().toISOString()},{org_id,employee_id:employees![1].id,clock_in:new Date(Date.now()-7*3600000).toISOString()}]);
 await db.from("ledger_entries").insert([{org_id,type:"income",category:"Services",description:"Studio Kindred retainer",amount:12500},{org_id,type:"expense",category:"Software",description:"Team tools",amount:1280},{org_id,type:"expense",category:"Operations",description:"Office supplies",amount:640}]);
 await db.from("purchase_orders").insert({org_id,vendor_id:vendor.id,po_number:"PO-2026-001",status:"approved",total:1480,items:[{description:"Office starter kits",quantity:10,price:148}]});
 await runAutomations(db,org_id,"deal.won",deals![0]);await runAutomations(db,org_id,"inventory.low",items![0]);await runAutomations(db,org_id,"leave.approved",leave);
 return NextResponse.json({ok:true,rules:rules?.length})}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
